In [1]:
# Load Libraries
import os
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error

In [2]:
# Load dataset
df = pd.read_csv('/Users/jaishreejoshita/Desktop/Loan_Data.csv')
df

,customer_id,credit_lines_outstanding,loan_amt_outstanding,total_debt_outstanding,income,years_employed,fico_score,default
0,8153374,0,5221.545193,3915.471226,78039.38546,5,605,0
1,7442532,5,1958.928726,8228.752520,26648.43525,2,572,1
2,2256073,0,3363.009259,2027.830850,65866.71246,4,602,0
3,4885975,0,4766.648001,2501.730397,74356.88347,5,612,0
4,4700614,1,1345.827718,1768.826187,23448.32631,6,631,0
...,...,...,...,...,...,...,...,...
9995,3972488,0,3033.647103,2553.733144,42691.62787,5,697,0
9996,6184073,1,4146.239304,5458.163525,79969.50521,8,615,0
9997,6694516,2,3088.223727,4813.090925,38192.67591,5,596,0
9998,3942961,0,3288.901666,1043.099660,50929.37206,2,647,0
9999,5533570,1,1917.652480,3050.248203,30611.62821,6,757,0

In [5]:
fico_scores = df['fico_score'].values
fico_scores

array([605, 572, 602, ..., 596, 647, 757])

In [26]:
from scipy.optimize import minimize
import numpy as np

# Sample data (FICO scores and corresponding ratings)
fico_scores = np.array([600, 650, 680, 720, 750, 780, 800, 850])
ratings = np.array([5, 4, 4, 3, 3, 2, 2, 1])

# Initial boundaries (evenly distributed)
initial_boundaries = np.linspace(min(fico_scores), max(fico_scores), num_buckets + 1)

# Define a likelihood function
def likelihood(boundaries):
    bucket_indices = np.digitize(fico_scores, boundaries)
    bucket_means = [np.mean(ratings[bucket_indices == i]) for i in range(1, num_buckets + 1)]
    predicted_ratings = np.array([bucket_means[i - 1] for i in bucket_indices])
    log_likelihood = -np.sum(np.log(np.exp(-np.abs(ratings - predicted_ratings)) + 1))
    return log_likelihood

# Optimize boundaries using log-likelihood
result = minimize(likelihood, initial_boundaries[1:-1], bounds=[(min(fico_scores), max(fico_scores))] * (num_buckets - 1))

# Extract the optimized boundaries
optimized_boundaries = np.concatenate(([min(fico_scores)], result.x, [max(fico_scores)]))

print("Optimized Bucket Boundaries (Log-Likelihood):", optimized_boundaries)

Optimized Bucket Boundaries (Log-Likelihood): [600.  662.5 725.  787.5 850. ]

/Users/rohitkumawat/opt/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3419: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/rohitkumawat/opt/anaconda3/lib/python3.9/site-packages/numpy/core/_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)